keyboard_words = {        
    "a":"air",
    "b":"bat",
    "c":"cap",
    "d":"dip",
    "e":"each",
    "f":"far",
    "g":"gone",
    "h":"harp",
    "i":"silt",
    "j":"jury",
    "k":"crunch",
    "l":"look",
    "m":"mad",
    "n":"near",
    "o":"odd",
    "p":"pit",
    "q":"quench",
    "r":"red",
    "s":"sun",
    "t":"trap",
    "u":"urge",
    "v":"vest",
    "w":"whale",
    "x":"plex",
    "y":"yank",
    "z":"zip",
} 


